### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by Lisek573** [Highlogic/stepmania-event#17]
Cannot compile this with CMake. Would it be possible to provide *.exe file?

**Comment by electromuis** [comment]
I shall do my best to post an alpha release this week

**Comment by nieknooijens** [comment]
I cannot provide .exe files myself maybe @electromuis can.
I'm running linux and I can't use the minGW cross compiler because stepmania on win32 requires directX and that's not available on linux.
@electromuis use depwalker to see which DLL's it's linking to and make sure you provide the correct versions of those! (welcome in windows' DLL-hell!) since windows doesn't have any decent package management system and there's no central directory for libraries so you still have to provide them with the binary in order for it to even work.

**Comment by Lisek573** [comment]
@electromuis thank you :)

**Comment by Lisek573** [comment]
@electromuis any update on the issue?

**Comment by electromuis** [comment]
https://github.com/Highlogic/stepmania-event/wiki
